[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.48"
dotenvy = "0.15"
regex = "1.10.5"

